version: "3"
services:
  web:
    image: "0kami/botnets:zeus"
    volumes:
      - ./bot:/var/www/html/bot
    ports:
      - "80:80"
    privileged: true
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: "mysql:5.6"
    environment:
      MYSQL_ROOT_PASSWORD: "your_password" # 修改数据库密码
      TZ: 'Asia/Shanghai'
    command: ['mysqld', '--character-set-server=utf8']
